# Generated by Django 3.1.3 on 2021-01-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitnessClass', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classDate', models.DateField(default=None)),
                ('reservationStatus', models.CharField(default=None, max_length=20)),
                ('reservationDate', models.DateField(default=None)),
                ('reservationTime', models.TimeField(default=None)),
                ('waitNumber', models.IntegerField(default='0')),
                ('classReserved', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitnessClass.fitnessclass')),
                ('customerReserving', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
