# Generated by Django 3.1.3 on 2020-12-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitnessClass', '0006_auto_20201229_1753'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classReserved', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitnessClass.fitnessclass')),
                ('customerReserving', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
