# Generated by Django 3.1.3 on 2020-12-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClass', '0006_auto_20201229_1753'),
        ('accounts', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
