# Generated by Django 3.1.3 on 2021-01-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationDate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservationTime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='waitNumber',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
