# Generated by Django 3.1.3 on 2021-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210102_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationTime',
            field=models.TimeField(default=None),
        ),
    ]
