# Generated by Django 3.1.3 on 2020-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201229_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(default=None),
        ),
    ]
