# Generated by Django 3.1.3 on 2020-12-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_reservationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='classDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationStatus',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='waitListNumber',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
