# Generated by Django 3.1.3 on 2021-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='waitNumber',
            field=models.IntegerField(default='0', max_length=20),
        ),
    ]
