# Generated by Django 3.1.3 on 2021-01-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210102_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='wait',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
