# Generated by Django 3.1.3 on 2021-01-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClass', '0008_delete_waitlist'),
        ('accounts', '0003_auto_20201230_1732'),
        ('reservations', '0005_auto_20201231_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationDate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='waitListNumber',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationDateTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDateTime', models.DateTimeField(default=None)),
                ('classId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitnessClass.fitnessclass')),
                ('customerId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
