# Generated by Django 3.1.3 on 2021-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_reservationdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(default=None),
        ),
    ]
