# Generated by Django 3.1.3 on 2021-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_reservationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationDateTime',
            field=models.DateField(default=None),
        ),
    ]
