# Generated by Django 3.1.3 on 2021-01-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_reservationdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationDate',
        ),
    ]
