# Generated by Django 3.1.3 on 2021-01-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_reservation_reservationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservationDateTime',
            new_name='reservationDate',
        ),
    ]
