# Generated by Django 3.1.3 on 2021-01-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20210101_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
