# Generated by Django 3.1.3 on 2021-01-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_delete_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateTimeField(default=None),
        ),
    ]
