# Generated by Django 3.1.3 on 2021-01-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20210101_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
