# Generated by Django 3.1.3 on 2021-01-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20210101_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationTimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(default=None),
        ),
    ]
