# Generated by Django 3.1.3 on 2021-01-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20210101_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationDate',
        ),
    ]
