# Generated by Django 3.1.3 on 2021-01-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_reservation_reservationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationTimeStamp',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationTime',
            field=models.TimeField(default=None),
        ),
    ]
