# Generated by Django 3.1.3 on 2021-01-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20210101_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
