# Generated by Django 3.1.3 on 2021-01-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='verfied',
            new_name='verified',
        ),
    ]
