# Generated by Django 3.1.3 on 2020-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verfied',
            field=models.CharField(choices=[('Annual', 'Annual Pass Holder'), ('Resident', 'Town of Leesburg Resident')], default=None, max_length=20),
        ),
    ]
