# Generated by Django 3.1.3 on 2021-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210103_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verified',
            field=models.CharField(choices=[('Annual', 'Annual Pass Holder'), ('Resident', 'Town of Leesburg Resident'), ('Neither', 'Neither'), ('UnVerified', 'UnVerified')], max_length=20),
        ),
    ]
