# Generated by Django 3.1.3 on 2020-12-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_verfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verfied',
            field=models.CharField(choices=[('Annual', 'Annual Pass Holder'), ('Resident', 'Town of Leesburg Resident'), ('Not Verified', 'Not Verified')], default='Not Verified', max_length=20),
        ),
    ]
