# Generated by Django 3.1.3 on 2020-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=100)),
                ('instructorName', models.CharField(max_length=100)),
                ('dayOfWeek', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday')], default=None, max_length=20)),
                ('startTime', models.TimeField(default=None)),
                ('endTime', models.TimeField(default=None)),
                ('maximumCapacity', models.CharField(max_length=20)),
            ],
        ),
    ]
