# Generated by Django 3.1.3 on 2020-12-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='endTime',
            field=models.TimeField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='startTime',
            field=models.TimeField(default=None, max_length=20),
        ),
    ]
