# Generated by Django 3.1.3 on 2020-12-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClass', '0005_auto_20201226_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='dayOfWeek',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=None, max_length=20),
        ),
    ]
