# Generated by Django 3.1.3 on 2020-12-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201230_1732'),
        ('fitnessClass', '0006_auto_20201229_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDateTime', models.DateTimeField(default=None)),
                ('classId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitnessClass.fitnessclass')),
                ('customerId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
