# Generated by Django 3.1.3 on 2021-01-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessClass', '0007_waitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
